### ISSUE TITLE
Mobile: Title Section Background (Hero image) not displaying

### ISSUE THREAD

**Issue by kimcartwright** [dcartwright07/hec-theme-eyecare#6]
On the mobile version, the background Hero images are not displaying.

**Comment by dcartwright07** [comment]
Same issue as Issue #5. Images were using the URL that include the _hamiltoneyecarecenter.com_ instead of _hamiltoneyecare.biz_. We will probably have to readjust these when the site goes live.

You can adjust these by going to the **Title Section** and updating the URL link.

**Example:** See the page technology. I update the **Title Section** there.
